name: 'Vader'
on: ['push']
jobs:
  vader:
    name: 'vader'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        vimFlavor: ['vim', 'nvim']
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'
    - name: 'Enable Universe package repository'
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
    - name: 'Install ${{ matrix.vimFlavor }}'
      run: |
        sudo apt-get install ${{ matrix.vimFlavor == 'nvim' && 'neovim' || 'vim' }}
    - name: 'Review versions'
      run: |
        ${{ matrix.vimFlavor }} --version
    - name: 'Fetch Vader'
      run: |
        git clone --depth 1 https://github.com/junegunn/vader.vim.git
    - name: 'Run test suite'
      timeout-minutes: 2
      run: |
        export VIM_CMD=${{ matrix.vimFlavor }}
        export VIM_FLAGS="${{ matrix.vimFlavor == 'nvim' && ' --headless' || ' -N' }}"
        export VIM_PLUGINS='..'
        bash ./tests/run.sh
